language: python
jobs:
    include:
        - name: "Python 3.9.0 on Linux"
          os: linux
          dist: xenial
          python: 3.9.0
        - name: "Python 3.9.0 on macOS"
          os: osx
          osx_image: xcode12.5
          python: 3.9.0
addons:
    apt:
        packages:
            - python3-pip
install:
    - pip3 install -r requirements.txt
