language: python
os: linux
dist: xenial
python: 3.9.0
addons:
    apt:
        packages:
            - python3-pip
before_install:
    - pip3 install pytest
install:
    - pip3 install -r requirements.txt
script:
    - pytest test.py
